---
abstract: 'A simple trie'
author:
  - 'Logan Bell <loganbell@gmail.com>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Simple-Trie
requires:
  Moo: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Simple-Trie
  homepage: http://metacpan.org/release/Simple-Trie
  repository: git://github.com/logie17/simple-trie.git
version: 0.01
x_Dist_Zilla:
  perl:
    version: 5.016002
  plugins:
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Author::LOGIE/TestMoreDoneTesting'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::LOGIE/GatherDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::LOGIE/PruneCruft'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::LOGIE/ManifestSkip'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::LOGIE/MetaYAML'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::LOGIE/License'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::LOGIE/Readme'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::LOGIE/ExtraTests'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::LOGIE/ExecDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::LOGIE/ShareDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::LOGIE/MakeMaker'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::LOGIE/Manifest'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::LOGIE/TestRelease'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::LOGIE/ConfirmRelease'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::LOGIE/MetaConfig'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::LOGIE/MetaJSON'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::LOGIE/NextRelease'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@Author::LOGIE/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::LOGIE/PkgVersion'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::LOGIE/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::LOGIE/PodCoverageTests'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::LOGIE/PodSyntaxTests'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Author::LOGIE/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::LOGIE/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Author::LOGIE/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Metadata
      name: '@Author::LOGIE/Metadata'
      version: 3.03
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@Author::LOGIE/MetaResources'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::LOGIE/Git::Check'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::LOGIE/Git::Commit'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::LOGIE/Git::Tag'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::LOGIE/Git::NextVersion'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::LOGIE/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::LOGIE/UploadToCPAN'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::LOGIE/Twitter'
      version: 0.020
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300030
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300030
x_authority: cpan:LOGIE
